apiVersion: v1
kind: Service
metadata:
  name: pagamentos-service
  labels:
    app: pagamentos
spec:
  selector:
    app: pagamentos
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
  type: LoadBalancer